### ISSUE TITLE
Cabal file dependency constraints need updated

### ISSUE THREAD

**Issue by sfogarty** [yamadapc/haskell-drawille#8]
The constraints on the containers package causes the project to not build on the most recent versions of haskell. Updating the containers requirement to `containers >=0.5 && <0.7`, to incorporate the newest `6.5` containers version, seems to fix the issue.

**Comment by yamadapc** [comment]
I have uploaded https://hackage.haskell.org/package/drawille `v0.1.3.0` with the suggestion; let me know if that is not enough to fix your issue.

All the best, Pedro
